### ISSUE TITLE
High CPU usage with Spigot

### ISSUE THREAD

**Issue by antoniotorresm** [AshDevFr/docker-spigot#15]
Apparently, if stdin is disconnected (when it is service mode) Spigot will up CPU usage to 100%. Adding the `--noconsole` to the jar run options should fix it.

https://www.spigotmc.org/threads/high-cpu-usage-solved.87634/page-2

**Comment by antoniotorresm** [comment]
I can open a PR to fix this, but I think it breaks `docker attach` usage.

**Comment by AshDevFr** [comment]
Hi, I added an option to disable the console. Let's hope it will fix the issue
```docker run -d -e NOCONSOLE=true```
