### ISSUE TITLE
UID not working

### ISSUE THREAD

**Issue by ghost** [AshDevFr/docker-spigot#18]
I tried to use the UID to 1001 according to the documentation. However, everytime I start the minecraft container my volume still gets chowned to user 1000. 

Here is my docker-compose.yml:

    version: "2"
     
    services:
        minecraft:
        image: ashdev/minecraft-spigot:latest
        restart: unless-stopped
        environment:
            - EULA=true
            - REV=1.15.2
            - JVM_OPTS=-Xmx8192M -Xms8192M
            - UID=1001
        ports:
            - '25566:25565'
        volumes:
            - ./data:/minecraft

**Comment by AshDevFr** [comment]
HI, yeah I think it's not working anymore. I might just remove the options
