### ISSUE TITLE
chmod -R causes delay with dynmap servers

### ISSUE THREAD

**Issue by cedarrapidsboy** [AshDevFr/docker-spigot#4]
For servers running dynmap, the "chmod -R minecraft.minecraft" can cause a massive delay when starting the server. For example, my world has generated millions of dynmap files in the plugins folder. Server startup was delayed by multiple minutes.

Workarounds:

* Use DB option for dynmap (possibly based on an ENV)
* Disable chmod step in the startup file (possibly based on an ENV)

This is a great Minecraft docker solution. Thank you.

**Comment by AshDevFr** [comment]
Hi @cedarrapidsboy, thank you for using this image.
I don't plan on using a DB for dynmap yet, but I'll look into it soon.
I added an option to skip the `chmod`, just add `SKIPCHMOD=true` in your env:

`docker run -d -e SKIPCHMOD=true`

**Comment by cedarrapidsboy** [comment]
Thanks!

I pretty quickly ran into an issue disabling chmod in my earlier workaround -- I subsequently added a plugin and forgot to chmod manually, so startup failed a bit.

I switched dynmap from filetree to SQLite (single file DB) and startup is again fast with chmod enabled. SQLite requires only an edit to the dynmap configuration.txt file:

    # Filetree storage (standard tree of image files for maps)
    #type: filetree
    # SQLite db for map storage (uses dbfile as storage location)
    type: sqlite
    dbfile: dynmap.db

**Comment by AshDevFr** [comment]
As using SQL with dynmap is just an option to change in the config file, I won't change the script. 
If the repository is mounted it is pretty easy to access the config file and change it.
