### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by mathvav** [AshDevFr/docker-spigot#9]
What is the license of this code?

**Comment by AshDevFr** [comment]
Hum I have not really thought about it. Are you trying to use it for commercial use ?

**Comment by mathvav** [comment]
No, just personal usage, but I might fork/make some modifications later and I like to make sure there's a clear license before I do anything like that.

I might personally recommend the MIT since it's short and sweet. You asked about commercial use and that is obviously not protected against by the MIT license, but I'm not sure that's really necessary for such a small codebase.

Of course, licensing is a personal decision and it's your intellectual property so you can license it as you please, but those are my two cents.

**Comment by AshDevFr** [comment]
I was also thinking about MIT which I use on other repositories. Let me  update the repository so it will be specified. Thank you for the heads up.
